// eslint-disable-next-line import/no-anonymous-default-export
export default {
  BOARDS_FETCH: 'BOARDS_FETCH',
  SKIPBO_GAMES_FETCH: 'SKIPBO_GAMES_FETCH',
  SKIPBO_GAMES_ADD: 'SKIPBO_GAMES_ADD',
  SKIPBO_GAMES_DELETE: 'SKIPBO_GAMES_DELETE',

  SKIPBO_GAMES_WINNERS_FETCH: 'SKIPBO_GAMES_WINNERS_FETCH',

  SKIPBO_STATISTICS_GENERAL_FETCH: 'SKIPBO_STATISTICS_GENERAL_FETCH',
  SKIPBO_STATISTICS_GAMES_HISTORY_FETCH: 'SKIPBO_STATISTICS_GAMES_HISTORY_FETCH',
  SKIPBO_STATISTICS_GAMES_PER_WINNER_FETCH: 'SKIPBO_STATISTICS_GAMES_PER_WINNER_FETCH',
  SKIPBO_STATISTICS_LAST_PLAY_DAY_GAMES_FETCH: 'SKIPBO_STATISTICS_LAST_PLAY_DAY_GAMES_FETCH',

  LIGHT_GROUPS_FETCH: 'LIGHT_GROUPS_FETCH',
  LIGHT_GROUP_UPDATE: 'LIGHT_GROUP_UPDATE',

  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  REFRESH_TOKEN: 'REFRESH_TOKEN',

  USER_UPDATE: 'USER_UPDATE',
};
