export const BOARDS = {
  FETCH_REQUEST: 'BOARDS/FETCH_REQUEST',
  FETCH_SUCCESS: 'BOARDS/FETCH_SUCCESS',
  FETCH_FAILURE: 'BOARDS/FETCH_FAILURE',
};

export const SKIPBO_GAMES = {
  FETCH_REQUEST: 'SKIPBO_GAMES/FETCH_REQUEST',
  FETCH_SUCCESS: 'SKIPBO_GAMES/FETCH_SUCCESS',
  FETCH_FAILURE: 'SKIPBO_GAMES/FETCH_FAILURE',

  DELETE_REQUEST: 'SKIPBO_GAMES/DELETE_REQUEST',
  DELETE_SUCCESS: 'SKIPBO_GAMES/DELETE_SUCCESS',
  DELETE_FAILURE: 'SKIPBO_GAMES/DELETE_FAILURE',
};

const actionTypes = {
  BOARDS,
  SKIPBO_GAMES,
};

export default actionTypes;
